name: Create Release

on: 
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Publish
        run: |
          yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}